### ISSUE TITLE
Pointer Events

### ISSUE THREAD

**Issue by lozandier** [akauppi/SvgBind#2]
I notice there's a `touchstart` event, but no `pointerdown` event?

**Comment by akauppi** [comment]
Hi @lozandier. 

What are the implications of that? I'm developing this on the OS X (testing on Safari and Chrome) and dragging by mouse pointer works fine. 

The event handling is based on [svg.draggable.js](https://github.com/wout/svg.draggable.js/tree/master) which does not deal with `pointerdown`, either.

Is `pointerdown`something IE specific?

**Comment by lozandier** [comment]
Hi, @akauppi: `pointerdown` & other pointed events are the most agnostic way of handling events associated with various types of input—including but not limited to touch, styluses, mouse & etc. Think of it as unified event system.

 Its events are prefixed with `pointer` to acknowledge the fact its events can be started by a finger, `pen`, or a traditional `mouse`.  Pointer events essentially  provide a more unified, responsive input model for all devices and input types than anything we had available on the Web.

It's available in Chrome, Android devices, & Microsoft products such as Surface. Microsoft proposed it. 

It's seen by the web community as the preferred way of handling events by various ways of input by end users of the web but had contention at first because of touch events such as `touchstart` that aided _some_ concerns associated with the limitations click events once had, also alleviating touch delays & etc.

At one point it was dropped but brought back swiftly with the limitations of touch events being more obvious. Nonetheless, important projects  such as the jQuery Foundation's '[PEP.js](https://github.com/jquery/PEP)' (note it does _not_ need jQuery; was created by Google & transferred to the jQuery foundation) & [Hammer.js](http://hammerjs.github.io) have normalized or accounted for its availability (or vice-versa).

**Comment by akauppi** [comment]
Thanks, @lozandier for the good explanation.

It seems like `pointerdown` and others are playing a similar role to `svg.rx.js`, in a way. What I mean by this is that the `svg.rx.js` API hides away any differences or inconveniences of the mouse vs. touch systems, and various slightly differing implementations of them (e.g. the way touch id's are generated in Android vs. iOS). 

For this reason, I don't see users of the `svg.rx.js` would really be affected by whether it's implemented using one event system over another. Which means those probably don't need supporting. However, I would very much invite you (and others) to test the current demos with Microsoft touch devices. Do they work? If not, that is the issue that should be handled.

In the mean time, I will read some more on `pointer*` to see whether I understood them right.

**Comment by lozandier** [comment]
Understood; FWIW, RxJS libs/extensions like RxDOM traditionally accounts
for events like pointer events as far as listening/recognizing 'em

On Thursday, January 7, 2016, Asko Kauppi notifications@github.com wrote:

> Thanks, @lozandier https://github.com/lozandier for the good
> explanation.
> 
> It seems like pointerdown and others are playing a similar role to
> svg.rx.js, in a way. What I mean by this is that the svg.rx.js API hides
> away any differences or inconveniences of the mouse vs. touch systems, and
> various slightly differing implementations of them (e.g. the way touch id's
> are generated in Android vs. iOS).
> 
> For this reason, I don't see users of the svg.rx.js would really be
> affected by whether it's implemented using one event system over another.
> Which means those probably don't need supporting. However, I would very
> much invite you (and others) to test the current demos with Microsoft touch
> devices. Do they work? If not, that is the issue that should be handled.
> 
> In the mean time, I will read some more on pointer\* to see whether I
> understood them right.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/akauppi/svg.rx.js/issues/2#issuecomment-169796903.

## 

Kevin Lozandier
lozandier@gmail.com lozandier@gmail.com

**Comment by akauppi** [comment]
Yes, but ´svg.rx.js` is not only about that, as you can see by checking the source code.

**Comment by akauppi** [comment]
For reference, the support does not seem as wide as you wrote: http://caniuse.com/#search=pointerdown
